# Generated by Django 6.0.3 on 2026-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_message', '0003_alter_message_chat_alter_message_options_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='messages/media/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
