# Generated by Django 6.0.3 on 2026-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
