# Generated by Django 6.0.3 on 2026-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusfeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='content',
        ),
        migrations.RemoveField(
            model_name='status',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='image_url',
        ),
        migrations.AddField(
            model_name='status',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='status/'),
        ),
        migrations.AddField(
            model_name='status',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
